[project]
name = "evaluation-quick-start"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "langsmith>=0.4.13",
    "openai>=1.99.6",
    "openevals>=0.1.0",
]
